baseURL = "https://www.dualdarker.com/"
languageCode = "en-us"
# ã€°ï¸â¿â°ğŸ•³ğŸ”®ğŸŒ‘ğŸŒš
title = "Dewell â¿ Darker"
theme = "dedarker"

# [permalinks]
#	blog = "/:filename/"

[params]
	dateFormat = "2006 Jan 02"
	description = "Trying to process my thoughts through work"
	images = ["img/2021_02_17-09_21_46-site.png"]

[markup.goldmark.renderer]
	unsafe= true
